# Generated by Django 3.0 on 2019-12-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_code', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'Farmer',
            },
        ),
        migrations.CreateModel(
            name='Fieldman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Fieldman',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=70)),
                ('middle_name', models.CharField(blank=True, max_length=70, null=True)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('age', models.CharField(default='', max_length=70)),
                ('gender', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='PersonFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('FR', 'Father of'), ('MR', 'Mother of'), ('SR', 'Son of'), ('DR', 'Daughter of'), ('BR', 'Brother of'), ('TR', 'Sister of'), ('GR', 'grandson of'), ('HR', 'husband of'), ('WR', 'wife of')], max_length=32)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farm.Person')),
                ('relative_of', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relative', to='farm.Person')),
            ],
            options={
                'db_table': 'PersonFamily',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name'], name='first_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'middle_name', 'last_name', 'age')},
        ),
        migrations.AddField(
            model_name='fieldman',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farm.Person'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farm.Person'),
        ),
        migrations.AddIndex(
            model_name='fieldman',
            index=models.Index(fields=['person'], name='Fieldman_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['farmer_code'], name='ryot_code_idx'),
        ),
    ]
