# Generated by Django 3.0 on 2019-12-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='farmer', to='farm.Person'),
        ),
        migrations.AlterField(
            model_name='fieldman',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fieldman', to='farm.Person'),
        ),
        migrations.AlterField(
            model_name='personfamily',
            name='relative_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatives', to='farm.Person'),
        ),
    ]
